AppVerk\UserBundle\Model\User:
    type: mappedSuperclass
    gedmo:
        soft_deleteable:
            field_name: deletedAt
    fields:
        username:
            type: string
            scale: 0
            length: null
            unique: true
            nullable: false
            precision: 0
        firstName:
            type: string
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: first_name
        lastName:
            type: string
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: last_name
        email:
            type: string
            scale: 0
            length: null
            unique: true
            nullable: false
            precision: 0
        password:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
        salt:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: true
            precision: 0
        enabled:
            type: boolean
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        passwordRequestedAt:
            type: datetime
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: password_requested_at
        passwordRequestToken:
            type: string
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: password_request_token
        phone:
            type: string
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
    lifecycleCallbacks: {  }
